
export const teamAbbreviations: { [key: string]: string } = {
    "Arsenal": "ARS",
    "Aston Villa": "AVL",
    "Bournemouth": "BOU",
    "Brentford": "BRE",
    "Brighton": "BHA",
    "Chelsea": "CHE",
    "Crystal Palace": "CRY",
    "Everton": "EVE",
    "Fulham": "FUL",
    "Liverpool": "LIV",
    "Man City": "MCI",
    "Man Utd": "MUN",
    "Newcastle": "NEW",
    "Nott'm Forest": "NFO",
    "Sunderland": "SUN",
    "Spurs": "TOT",
    "West Ham": "WHU",
    "Wolves": "WOL",
    "Burnley": "BUR",
    "Leeds": "LEE",

    // Less common teams, will keep for robustness, but prioritize exact matches from JSON
    "Ipswich Town": "IPS",
    "Leicester City": "LEI",
    "Southampton": "SOU",
    "West Bromwich Albion": "WBA",
    "Sheffield United": "SHU",
    "Watford": "WAT",
    "Norwich City": "NOR",
    "Stoke City": "STK",
    "Sheffield Wednesday": "SHW",
    "Middlesbrough": "MID",
    "Hull City": "HUL",
    "Cardiff City": "CAR",
    "Huddersfield Town": "HUD",
    "Swansea City": "SWA",
};
